#!/usr/bin/env python3
"""Generate the NFL-wide files from the per-team tables (a join, never an agent):
nfl/injuries-and-designations.md, successor-map.md, rookies-and-young-players.md,
hype-and-reports.md, suspensions-and-legal.md, coaching-and-scheme-<season>.md,
coach-tendencies.md, defense-tendencies.md, offensive-lines.md. Run after every rewrite
or refresh, after kb-lint.py passes. The nfl/ folder is created when it is not there.

--season is REQUIRED and is never derived from --date: a refresh run in January belongs
to the season that just ended, not to the calendar year, and a season guessed from the
date would name the wrong file and grep the wrong heading. Everything the season touches
is computed from it: the coaching file's name and title, the defence heading this reads
out of the profiles ("(<season-1> basis)"), the rookies header's games-missed span, and
the ratings file the defence rollup points at. A --season that no profile's defence
heading agrees with stops the run before anything is written, rather than writing a
defence table of "-" cells and exiting 0.

    python3 rollups.py --dir <kb> --date YYYY-MM-DD --season N
"""
import argparse, glob, os, re

ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
ap.add_argument('--dir', required=True); ap.add_argument('--date', required=True)
ap.add_argument('--season', type=int, required=True)
a = ap.parse_args(); K, D, S = a.dir, a.date, a.season
if S < 1900: raise SystemExit('--season must be a four-digit year')
prior = S - 1
span = f'{S - 3}-{prior % 100:02d}'
GIVES = f'## Gives up by position ({prior} basis)'

def table(text, heading):
    """Rows (as cell lists) of the first table under a heading."""
    lines = text.split('\n')
    i = next((k for k, l in enumerate(lines) if l.strip() == heading), -1)
    if i < 0: return []
    j = i + 1
    while j < len(lines) and not lines[j].startswith('|'): j += 1
    j += 2; rows = []
    while j < len(lines) and lines[j].startswith('|'):
        rows.append([c.strip() for c in lines[j].strip().strip('|').split('|')]); j += 1
    return rows

def bullets(text, heading):
    lines = text.split('\n')
    i = next((k for k, l in enumerate(lines) if l.strip() == heading), -1)
    if i < 0: return []
    out = []
    for l in lines[i + 1:]:
        if l.startswith('## '): break
        if l.startswith('- ') and l.strip() != '-' and l.strip() != '- -': out.append(l[2:].strip())
    return out

def head(text): return text.split('\n')[0]
def line2(text):
    """The staff line under the header, with its pipes turned into slashes so it fits one cell."""
    for l in text.split('\n')[1:6]:
        if l.strip(): return l.strip().replace('|', '/')
    return ''

teams = {}
for p in sorted(glob.glob(os.path.join(K, 'teams', '*.md'))):
    code = os.path.basename(p)[:-3]
    teams[code] = {'dossier': open(p, encoding='utf-8').read()}
    for kind, path in (('offense', f'coach/{code}-offense.md'), ('defense', f'coach/{code}-defense.md'), ('oline', f'oline/{code}.md')):
        fp = os.path.join(K, path)
        teams[code][kind] = open(fp, encoding='utf-8').read() if os.path.isfile(fp) else ''
codes = sorted(teams)

# A season that disagrees with the files is caught here, not absorbed. Without this the
# defence rollup finds no heading to read, writes "-" into every cell of every row and
# exits 0, which looks like a clean run and is a silently emptied file.
have_defense = [c for c in codes if teams[c]['defense']]
if have_defense and not any(GIVES in teams[c]['defense'] for c in have_defense):
    raise SystemExit(f'no profile carries "{GIVES}"; --season {S} does not match the knowledgebase')

def write(name, body):
    # The first build of a season runs before anything has created nfl/, so make it here
    # rather than ending the build in a traceback.
    out = os.path.join(K, 'nfl'); os.makedirs(out, exist_ok=True)
    open(os.path.join(out, name), 'w', encoding='utf-8').write(body.rstrip('\n') + '\n')
    print('wrote', name)
GEN = f'Generated by build/rollups.py from the per-team tables on {D}; never hand-edited. Edit the team file and rerun.'

# 1. injuries and designations (every room row whose Status is not healthy)
rows = []
for c in codes:
    for r in table(teams[c]['dossier'], '## Rooms'):
        if len(r) >= 8 and r[4] != '-' and not r[4].lower().startswith('healthy'):
            rows.append(f'| {c} | {r[0]} | {r[1]} | {r[3]} | {r[4]} | {r[5]} |')
write('injuries-and-designations.md', f'# Injuries and designations - refreshed {D}\n\n{GEN} One row per player not fully available, with the coach\'s stated replacement plan.\n\n| Team | Player | Pos | Role | Status | If out |\n|---|---|---|---|---|---|\n' + '\n'.join(rows))

# 2. successor map (every room row with an If-out call)
rows = []; young = []
for c in codes:
    for r in table(teams[c]['dossier'], '## Rooms'):
        if len(r) >= 8 and r[5] != '-':
            rows.append(f'| {c} | {r[0]} | {r[1]} | {r[3]} | {r[5]} |')
    for r in table(teams[c]['dossier'], '## Rookies and young players behind veterans'):
        if len(r) >= 7 and re.search(r'taking|rising', r[6], re.I):
            young.append(f'| {c} | {r[0]} | {r[1]} | {r[2]} | {r[6]} |')
write('successor-map.md', f'# Successor map - refreshed {D}\n\n{GEN} Who takes the role if the starter is out: PRIMARY (one man), COMMITTEE (a share) or UNSETTLED, with the source that made it so.\n\n| Team | Starter | Pos | Role | If out |\n|---|---|---|---|---|\n' + '\n'.join(rows) + '\n\n## Backfields and rooms shifting young\n\n| Team | Player | Pos | Veteran ahead | Verdict |\n|---|---|---|---|---|\n' + '\n'.join(young))

# 3. rookies and young players
rows = [f'| {c} | ' + ' | '.join(r) + ' |' for c in codes for r in table(teams[c]['dossier'], '## Rookies and young players behind veterans') if len(r) >= 7]
write('rookies-and-young-players.md', f'# Rookies and young players behind veterans - refreshed {D}\n\n{GEN}\n\n| Team | Player | Pos | Veteran ahead | Vet age | Vet games missed {span} | Evidence | Takeover verdict |\n|---|---|---|---|---|---|---|---|\n' + '\n'.join(rows))

# 4. hype and reports, grouped by tag
bytag = {}
for c in codes:
    for r in table(teams[c]['dossier'], '## Media read (last 14 days)'):
        if len(r) >= 4: bytag.setdefault(r[1].lower(), []).append(f'| {c} | {r[0]} | {r[2]} | {r[3]} |')
parts = [f'# Hype and reports (last 14 days) - refreshed {D}\n\n{GEN} Hype is labeled hype.']
for tag in sorted(bytag):
    parts.append(f'\n## {tag}\n\n| Team | Player | Outlets | Line |\n|---|---|---|---|\n' + '\n'.join(bytag[tag]))
write('hype-and-reports.md', '\n'.join(parts))

# 5. suspensions and legal
SUSP = re.compile(r'(?<!not )(?<!no )(?<!never )\b(suspended|commissioner exempt|exempt list)\b', re.I)
rows = [f'| {c} | {r[0]} | {r[1]} | {r[4]} |' for c in codes for r in table(teams[c]['dossier'], '## Rooms') if len(r) >= 8 and SUSP.search(r[4]) and not re.search(r'not (on the )?(exempt|suspended)', r[4], re.I)]
write('suspensions-and-legal.md', f'# Suspensions, exempt list and open reviews - refreshed {D}\n\n{GEN}\n\n| Team | Player | Pos | Status |\n|---|---|---|---|\n' + ('\n'.join(rows) if rows else '| - | none listed | - | - |'))

# 6. coaching and scheme (dossier header line 2)
rows = []
for c in codes:
    l = line2(teams[c]['dossier'])
    rows.append(f'| {c} | {l} |')
write(f'coaching-and-scheme-{S}.md', f'# Play callers and staffs {S} - refreshed {D}\n\n{GEN} NEW marks a caller or coordinator new to the team for {S}.\n\n| Team | Staff line |\n|---|---|\n' + '\n'.join(rows))

# 7. coach tendencies (roster fit by direction)
bydir = {}
for c in codes:
    for r in table(teams[c]['offense'], '## Roster fit'):
        if len(r) >= 4: bydir.setdefault(r[2].lower(), []).append(f'| {c} | {r[0]} | {r[1]} | {r[3]} |')
parts = [f'# Coach tendencies matched to rosters - refreshed {D}\n\n{GEN} Per-team detail and the six tendency rows live in coach/<CODE>-offense.md.']
for d in ('bounceback', 'step-forward', 'downgrade', 'unchanged'):
    if d in bydir: parts.append(f'\n## {d}\n\n| Team | Player | Pos | Driver |\n|---|---|---|---|\n' + '\n'.join(bydir[d]))
for d in sorted(k for k in bydir if k not in ('bounceback', 'step-forward', 'downgrade', 'unchanged')):
    parts.append(f'\n## {d}\n\n| Team | Player | Pos | Driver |\n|---|---|---|---|\n' + '\n'.join(bydir[d]))
write('coach-tendencies.md', '\n'.join(parts))

# 8. defense tendencies (matchup table by position)
rows = []
for c in codes:
    t = teams[c]['defense']; g = {r[0].upper(): r for r in table(t, GIVES) if r}
    cell = lambda p: (f'{g[p][1]} ({g[p][2]})' if p in g and len(g[p]) >= 3 else '-')
    rows.append(f'| {c} | {line2(t)} | {cell("QB")} | {cell("RB")} | {cell("WR")} | {cell("TE")} |')
write('defense-tendencies.md', f'# Defenses by position - refreshed {D}\n\n{GEN} Points allowed per game (rank, 1 = softest), {prior} basis; the weekly ratings and injury adjustments are in defense-ratings-{S}.md and schedule/<CODE>.md.\n\n| Team | Coordinator, scheme, pressure | QB | RB | WR | TE |\n|---|---|---|---|---|---|\n' + '\n'.join(rows))

# 9. offensive lines
rows = []
for c in codes:
    t = teams[c]['oline']; w = bullets(t, '## Watch')
    rows.append(f'| {c} | {line2(t)} | {w[0] if w else "-"} |')
write('offensive-lines.md', f'# Offensive lines - refreshed {D}\n\n{GEN} Rank, win rates, sacks, yards before contact and pressure per team; the starters and the player impact live in oline/<CODE>.md.\n\n| Team | Line | Watch |\n|---|---|---|\n' + '\n'.join(rows))
